use grid for index
htmlacademy-htmlcss/71520-sedona-30 pull request #7
Opened 2021-02-14 15:40 UTC by evilinyoursoul

5.17. Сетка на гридах для главной страницы
Если тут что-то драматически не так, то мне нужна консультация по гридам :)
Я их мучала несколько дней, и до сих пор не всё понимаю.

2021-02-14 15:45 UTC, evilinyoursoul commented
А еще валидатор ругается на div в ol, но как иначе выйти из ситуации - я не понимаю.

2021-02-14 17:05 UTC, Vallek requested changes
Привет! Драматически страшного нет:) Но я думаю все равно стоит провести консультацию. Особенно, если понимаешь, что что-то не понимаешь:)

1. Обрати внимание, что текст в пунктах меню выровнен по краям на макете.
2. Лого можно как вариант позиционированием расположить.
3. В интро уже пора фоновую картинку подключить.
3. По поводу гридов. Можно так сделать, но лучше попробовать задать общий. Это можно сделать с помощью display: contents. Могу показать на созвоне.
4. Обрати внимание, что высота блоков жилье, еда, сувениры отличается. И фоновый цвет тоже другой.
5. У некоторых элементов не сброшены свойства по умолчанию.
6. Размеры иконок в футере. Текст больше не нужен.
6. Всякие еще мелочи и не очень:) Можно это сделать, когда дойдешь до флексбокса конечно. 
7. В вебе как правило нельзя ограничивать высоту. Там, где может что-то поменяться.

Можем рассмотреть это все на созвоне:)

2021-02-22 15:22 UTC, evilinyoursoul commented
Здесь же обновила каталог. Верстать карточки гостиниц не хочу на гридах, хочу к флексам уже пойти :(

2021-02-22 17:09 UTC, Vallek reviewed
Привет! Раз гриды надоели, то надо флексбокс попробовать, да:) 

1. Не забудь скинуть стили по умолчанию. У списка меню остался отступ по умолчанию. Стоит все проверить.
2. Не забудь сверстать форму поиска, декоративные элементы, карту.

2021-02-22 17:12 UTC, merged